### ISSUE TITLE
How hard would it be to extend support to any git website using gitea? And other git services?

### ISSUE THREAD

**Issue by Kabouik** [skanehira/github-tui#14]
Would it be technically possible to extend functionality to other git domains using `gitea`? It's already great to have Github working of course since it's probably the biggest, but there are multiple other git websites that use `gitea` and could perhaps be interacted with similarly, if `ght` could be used like `ght domain.tld/maintainer/project` or `ght domain maintainer/project` instead of just `ght maintainer/project`

Ideally, `config.yaml` could take multiple tokens for different domains, and there could be an option to make one default (or, alternatively, the first domain listed could be default, so that it's not needed to prepend the domain for it when using `ght`), and `ght` would automatically use the corresponding token when trying to post/reply/edit a comment on the corresponding domain:

```
github:
  token: xxxxxxxxxxxxxxxxx
teknik:
  token: yyyyyyyyyyyyyyyyy
```

There could be an option to manually add the domain too if `ght` doesn't already know about it but it uses a known git service, like:

```
github:
  token: xxxxxxxxxxxxxxxxx
teknik:
  url: https://git.teknik.io
  token: yyyyyyyyyyyyyyyyy
```

And of course it would also be great if other git services like `gitlab` or `gogs` could be supported too so that issues on gitlab.com, notabug.org and others can be tracked too, but I imagine this would be a huge amount of work.
